# Docs: https://www.elastic.co/guide/en/beats/metricbeat/master/metricbeat-module-haproxy.html
- module: haproxy
  enabled: true
  metricsets:
    - info
    - stat
  period: 10s
  hosts: ["tcp://127.0.0.1:9091"]
