# Docs: https://www.elastic.co/guide/en/beats/metricbeat/master/metricbeat-module-nginx.html
- module: nginx
  metricsets:
    - stubstatus
  period: 10s
  hosts: ["https://<%= @fqdn %>"]
  server_status_path: "metricbeat-status"
  # we use self-signed certificates for our primary hostnames in many cases
  ssl.verification_mode: "none"
  #username: "user"
  #password: "secret"
