filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/cron

  exclude_lines: [
    'metricbeat\[',
    'filebeat\[',
    '\[UFW BLOCK\]'
  ]
  #include_lines: ['^ERR', '^WARN']
  # safeguard in case someone globs /var/log/*
  exclude_files: [
        '/var/log/lastlog',
        '/var/log/wtmp',
        '/var/log/filebeat/*',
        '/var/log/metricbeat/*'
  ]
  scan_frequency: 30s
  close_inactive: 5m
  clean_inactive: 48h
  backoff: 5s
  ignore_older: 24h

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true
  reload.period: <%= @reload_period %>
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 3
  permissions: 0600
  rotateeverybytes: 10485760
  rotateonstartup: true
logging.level: info
logging.metrics:
  enabled: true
  period: 1m
logging.to_eventlog: false
logging.to_files: true
logging.to_stderr: false
logging.to_syslog: false
#==================== Elasticsearch template setting ==========================
setup.ilm.enabled: false
setup.ilm.check_exists: false
setup.ilm.overwrite: false
setup.dashboards.enabled: false
setup.dashboards.retry.enabled: false
setup.template.enabled: false
setup.template.overwrite: false
setup.ilm.enabled: false
setup.ilm.check_exists: false
setup.ilm.overwrite: false

output.elasticsearch:
  hosts: ["<%= @elastic_host %>"]
  protocol: "https"
  username: "<%= @elastic_user %>"
  password: "<%= @elastic_pass %>"
  ssl.certificate_authorities:
    - "<%= @ssl_path_ca %>"
  compression_level: <%= @elastic_compression %>
  max_retries: <%= @elastic_max_retries %>
  bulk_max_size: <%= @elastic_bulk_max_size %>
  backoff.init: <%= @elastic_backoff_init %>
  backoff.max: <%= @elastic_backoff_max %>
  timeout: <%= @elastic_timeout %>

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

queue.mem:
 events: <%= @queue_events %>
 flush.min_events: <%= @queue_flush_min %>
 flush.timeout: <%= @queue_flush_timeout %>

logging.level: warning
monitoring.enabled: false
monitoring.elasticsearch: false
